//
//  Video.swift
//  My YouTube Channel
//
//  Created by Can Balkaya on 10/26/19.
//  Copyright © 2019 Can Balkaya. All rights reserved.
//

import UIKit

struct Video {
    var title: String
    var thumbnailUrl: String
    var url: String
}

var videos = [video47, video46, video45, video44, video43, video42, video41, video40, video39, video38, video37, video36, video35, video34, video33, video32, video31, video30, video29, video28, video27, video26, video25, video24, video23, video22, video21, video20, video19, video18, video17, video16, video15, video14, video13, video12, video11, video10, video9, video8, video7, video6, video5, video4, video3, video2, video1]

var video47 = Video(title: "Yeni iPhone Nasıl Olacak?", thumbnailUrl: "https://i.ytimg.com/vi/5F9sFFEcg6g/hqdefault.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLC3xGIeD6B9v_JYYK9pk6E_RIJTaQ", url: "https://www.youtube.com/watch?v=5F9sFFEcg6g")
var video46 = Video(title: "Bir Ömür Nasıl Yaşanır? - K. H.", thumbnailUrl: "https://i.ytimg.com/vi/RmSEk-9xxo4/hqdefault.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLD57AjTiHDqsgWtXjDP7QPYbEByJw", url: "https://www.youtube.com/watch?v=RmSEk-9xxo4")
var video45 = Video(title: "Pisagor Matematik Evi Nedir? - Haluk Memili / Röportajlar 1", thumbnailUrl: "https://i.ytimg.com/vi/-41r9kdjajE/hqdefault.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLABeHscb9Lj3FfNTY1DeAFyhEyMNg", url: "https://www.youtube.com/watch?v=-41r9kdjajE")
var video44 = Video(title: "NMK'lılar NMK Hakkında Ne Düşünüyor?", thumbnailUrl: "https://i.ytimg.com/vi/46JxA4-_1qk/hqdefault.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLBNPUljHXxDsK8tUGutcOgvvzem2w", url: "https://www.youtube.com/watch?v=46JxA4-_1qk")
var video43 = Video(title: "Yeniden NMK'dayım!", thumbnailUrl: "https://i.ytimg.com/vi/-i0XXVBUT90/hqdefault.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLClAfGx_yqnatvqZyyMqjKDjTwh7Q", url: "https://www.youtube.com/watch?v=-i0XXVBUT90")
var video42 = Video(title: "Bir Etkinlikte Basın Mensubu Olarak Yer Aldım! - 2019 Boğaziçi Kıtalararası Yüzme Yarışı", thumbnailUrl: "https://i.ytimg.com/vi/6p6SuHtbWN0/hqdefault.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLCJsxP7L0UnASLbzBr7jmbu1l8LVw", url: "https://www.youtube.com/watch?v=6p6SuHtbWN0")
var video41 = Video(title: "Her Şey Değişiyor!", thumbnailUrl: "https://i.ytimg.com/vi/8RdG9C5W-Ws/hqdefault.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLB6CbVbCZ81Qf0Hiz56JZh2lz0dzw", url: "https://www.youtube.com/watch?v=8RdG9C5W-Ws")
var video40 = Video(title: "Hızlı Kare Alma", thumbnailUrl: "https://i.ytimg.com/vi/4tJ5-pDxV4g/hqdefault.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLAZ3nHTiyGV2rX_ULaIpuVOLMtuUQ", url: "https://www.youtube.com/watch?v=4tJ5-pDxV4g")
var video39 = Video(title: "Bilmiyorum!", thumbnailUrl: "https://i.ytimg.com/vi/5mSPcc74jD4/hqdefault.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLDvmTHNgrMH64yLLB0dd-6h8i5kvg", url: "https://www.youtube.com/watch?v=EEMPMoKtJxY")
var video38 = Video(title: "Nereden Başlayalım: Eğitimin ABC'si", thumbnailUrl: "https://i.ytimg.com/vi/5mSPcc74jD4/hqdefault.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLDvmTHNgrMH64yLLB0dd-6h8i5kvg", url: "https://www.youtube.com/watch?v=5mSPcc74jD4")
var video37 = Video(title: "Hemen Fark Edilmeyen İçerik Üreticileri Ne Yapmalı?", thumbnailUrl: "https://i.ytimg.com/vi/-Y3JHSE7Ft8/hqdefault.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLC-yQHOadCRTTT5J5heeAADwU4rlg", url: "https://www.youtube.com/watch?v=-Y3JHSE7Ft8")
var video36 = Video(title: "1. Kuvvet Alanları - Olanaksızın Fiziği", thumbnailUrl: "https://i.ytimg.com/vi/RMdkirnA7cc/hqdefault.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLBdM_Z9Uaix0RFKnb2yKJ77TEIYng", url: "https://www.youtube.com/watch?v=RMdkirnA7cc")
var video35 = Video(title: "Kim Sömestir Tatilinde Challenge Yapmak İster?", thumbnailUrl: "https://i.ytimg.com/vi/V8fYY1ICM8w/hqdefault.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLAKIbC2_pHkdhaIAF0Ibk6J4-xjjQ", url: "https://www.youtube.com/watch?v=V8fYY1ICM8w")
var video34 = Video(title: "Trachtenberg Metodu Nedir?", thumbnailUrl: "https://i.ytimg.com/vi/BbCbUe6xzVg/hqdefault.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLCfZCaTkZqLWNwjSo0_Jw1GB3s_Cw", url: "https://www.youtube.com/watch?v=BbCbUe6xzVg")
var video33 = Video(title: "YGA Nedir?", thumbnailUrl: "https://i.ytimg.com/vi/1GNjKl462qo/hqdefault.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLDaynHaTrJxSuWHwFJ1J8EKegEVWg", url: "https://www.youtube.com/watch?v=1GNjKl462qo")
var video32 = Video(title: "2018 YGA Zirvesindeyim!", thumbnailUrl: "https://i.ytimg.com/vi/fj1sy0JnH8I/hqdefault.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLCIv_wpeMfZoXW4SAdTMVmzT4lI2g", url: "https://www.youtube.com/watch?v=fj1sy0JnH8I")
var video31 = Video(title: "Neden İçerik Üretiyorum?", thumbnailUrl: "https://i.ytimg.com/vi/SaTwQ4H_fRY/hqdefault.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLCHNy-QSpCRyYHqJUPUpZkrwVh6TA", url: "https://www.youtube.com/watch?v=SaTwQ4H_fRY")
var video30 = Video(title: "Dönüş", thumbnailUrl: "https://i.ytimg.com/vi/XSdnI30pMVA/hqdefault.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLAkNNf3HcMVWiqHqwbHTc9xJ4TSpw", url: "https://www.youtube.com/watch?v=XSdnI30pMVA")
var video29 = Video(title: "NMK'da 2. Hafta", thumbnailUrl: "https://i.ytimg.com/vi/n0wvkR8SwXM/hqdefault.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLC9kXzu9LIZibd9HHGEs6Zh5cueuw", url: "https://www.youtube.com/watch?v=n0wvkR8SwXM")
var video28 = Video(title: "Kısa bir NMK Gezisi", thumbnailUrl: "https://i.ytimg.com/vi/xIvECDFaVvM/hqdefault.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLBOsP2ttBkQ_kpr9ZYQxNtuPVz4uA", url: "https://www.youtube.com/watch?v=xIvECDFaVvM")
var video27 = Video(title: "NMK Neden Özel Bir Yer?", thumbnailUrl: "https://i.ytimg.com/vi/CuN6UEkpymI/hqdefault.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLCbpVi_eB1_whK6RE5VYysm8rRqHA", url: "https://www.youtube.com/watch?v=CuN6UEkpymI")
var video26 = Video(title: "NMK'da Bir Günüm Nasıl Geçiyor?", thumbnailUrl: "https://i.ytimg.com/vi/Ufx_BpZRQTE/hqdefault.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLDEnGBd76HAYseGK3xMxqwvTcuQUw", url: "https://www.youtube.com/watch?v=Ufx_BpZRQTE")
var video25 = Video(title: "NMK'da 1. Hafta", thumbnailUrl: "https://i.ytimg.com/vi/6PTsxskz8YI/hqdefault.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLA3d_nodR7f2D7WhxnCeEOL_GbesQ", url: "https://www.youtube.com/watch?v=6PTsxskz8YI")
var video24 = Video(title: "NMK'ya Gidiyorum", thumbnailUrl: "https://i.ytimg.com/vi/u_4ne0MRho0/hqdefault.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLB6KjK6t34zOLoFOLEPFAbWi5Ngrw", url: "https://www.youtube.com/watch?v=u_4ne0MRho0")
var video23 = Video(title: "NEDEN İLE BAŞLA (2. Kitap) - Kitaplar Hakkında", thumbnailUrl: "https://i.ytimg.com/vi/fz5ULqtIqUc/hqdefault.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLAFTMWpwISfkmANsXFUUYIHORWVDA", url: "https://www.youtube.com/watch?v=fz5ULqtIqUc")
var video22 = Video(title: "Yeni İçerikler Var!", thumbnailUrl: "https://i.ytimg.com/vi/eF-liyPy8xo/hqdefault.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLCQLHVgz1db9hfqzcmJHkHiJq4TZw", url: "https://www.youtube.com/watch?v=eF-liyPy8xo")
var video21 = Video(title: "Tau Sayısı Nedir?", thumbnailUrl: "https://i.ytimg.com/vi/a8b35AkyA6k/hqdefault.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLDelh7OUEqd9Mcs5zXmfW3aZBARTA", url: "https://www.youtube.com/watch?v=a8b35AkyA6k")
var video20 = Video(title: "NEDEN İLE BAŞLA (1. Kitap) - Kitaplar Hakkında", thumbnailUrl: "https://i.ytimg.com/vi/WF7fIgj68bg/hqdefault.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLC16xV8Zpvy1EHDk6KUBiidCFqKIA", url: "https://www.youtube.com/watch?v=WF7fIgj68bg")
var video19 = Video(title: "Bilimsiz gelişemeyiz", thumbnailUrl: "https://i.ytimg.com/vi/fTGvReocF_E/hqdefault.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLDHHpnDSJGrF1pwu2Ac7WNU8APbhA", url: "https://www.youtube.com/watch?v=fTGvReocF_E")
var video18 = Video(title: "türk aynştaynı - Kitaplar Hakkında", thumbnailUrl: "https://i.ytimg.com/vi/z0nu7jHYzR0/hqdefault.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLA0uZkXMb6Em_fzbGUJ84Vk-D9inA", url: "https://www.youtube.com/watch?v=z0nu7jHYzR0")
var video17 = Video(title: "iPad ile Geleceğin Eğitimi", thumbnailUrl: "https://i.ytimg.com/vi/LwOV9KwxR8E/hqdefault.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLBMiNB_dWWGsMjAH8ZqOTZMYi1OvA", url: "https://www.youtube.com/watch?v=LwOV9KwxR8E")
var video16 = Video(title: "Bayrak - Tiyatrolar Hakkında", thumbnailUrl: "https://i.ytimg.com/vi/TGTjxozBJyQ/hqdefault.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLCglhRGfKK6qIGxF-6aCbrMV5KF5w", url: "https://www.youtube.com/watch?v=TGTjxozBJyQ")
var video15 = Video(title: "İzlemek Ne Kadar Önemli?", thumbnailUrl: "https://i.ytimg.com/vi/S76V66kNxKA/hqdefault.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLAlrcm3cnsCy62qUtqIXI54C35Opg", url: "https://www.youtube.com/watch?v=S76V66kNxKA")
var video14 = Video(title: "1984 - Kitaplar Hakkında", thumbnailUrl: "https://i.ytimg.com/vi/Il9-SYmxSfo/hqdefault.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLBF-Hef0gzAF18lFUksK2JmUdnnDg", url: "https://www.youtube.com/watch?v=Il9-SYmxSfo")
var video13 = Video(title: "Okula Gidince Ne Oluyor?", thumbnailUrl: "https://i.ytimg.com/vi/0CxQC9R-DHk/hqdefault.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLBwDHYOFC6z9c19gMLFAedkqHzK0g", url: "https://www.youtube.com/watch?v=0CxQC9R-DHk")
var video12 = Video(title: "Karıncalar Bir Savaş Vardı - Tiyatrolar Hakkında", thumbnailUrl: "https://i.ytimg.com/vi/MONmLF5J1d4/hqdefault.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLBCcHW6NP_HJPBAojkVlee9AKReTg", url: "https://www.youtube.com/watch?v=MONmLF5J1d4")
var video11 = Video(title: "Falcon Heavy Bize Ne Anlatıyor?", thumbnailUrl: "https://i.ytimg.com/vi/wUj2iHCkcv8/hqdefault.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLCwvxhvgp6X2YSbQUiscL6NiEXG9g", url: "https://www.youtube.com/watch?v=wUj2iHCkcv8")
var video10 = Video(title: "\"BYE BYE\" Türkçe - Kitaplar Hakkında", thumbnailUrl: "https://i.ytimg.com/vi/2VoM26m-rMA/hqdefault.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLCqUhmonNBGcxkswjkoyK5q-QuX5Q", url: "https://www.youtube.com/watch?v=2VoM26m-rMA")
var video9 = Video(title: "İstanbul'da Bisiklete Binmek", thumbnailUrl: "https://i.ytimg.com/vi/lKRhsr8PEvI/hqdefault.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLCVtD4UsAcqYOcN19xR-daSM-zWOw", url: "https://www.youtube.com/watch?v=lKRhsr8PEvI")
var video8 = Video(title: "Dünya Okulu - Kitaplar Hakkında", thumbnailUrl: "https://i.ytimg.com/vi/50FzLitHobs/hqdefault.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLB3vNFteKjJNiiWsb80M85oh3J-3A", url: "https://www.youtube.com/watch?v=50FzLitHobs")
var video7 = Video(title: "İnovasyon Nerede?", thumbnailUrl: "https://i.ytimg.com/vi/kUHgqKsSVqA/hqdefault.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLDXcwWc1qcDnn3CgGKbSc_92cb4wg", url: "https://www.youtube.com/watch?v=kUHgqKsSVqA")
var video6 = Video(title: "Beyaz Zambaklar Ülkesinde - Kitaplar Hakkında", thumbnailUrl: "https://i.ytimg.com/vi/XNtHmK3y3pU/hqdefault.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLBPLqHjmelY-QU7pHaUF1O-mBJKXg", url: "https://www.youtube.com/watch?v=XNtHmK3y3pU")
var video5 = Video(title: "Kibarlık Budalası", thumbnailUrl: "https://i.ytimg.com/vi/e1yd6HC7vwI/hqdefault.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLCWyt3i6dhJUxOfP7T1-4TbluZl0w", url: "https://www.youtube.com/watch?v=e1yd6HC7vwI")
var video4 = Video(title: "Elon Musk - Kitaplar Hakkında", thumbnailUrl: "https://i.ytimg.com/vi/dLwas_iu4cE/hqdefault.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLAsCqed9vfHuZvvjT0vInDIsk--Mg", url: "https://www.youtube.com/watch?v=dLwas_iu4cE")
var video3 = Video(title: "Leyla'nın Evi - Tiyatrolar Hakkında", thumbnailUrl: "https://i.ytimg.com/vi/rvwtq1kzBW0/hqdefault.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLAlv4UuLqpLpZzXBQM2FMjX1pKDsg", url: "https://www.youtube.com/watch?v=rvwtq1kzBW0")
var video2 = Video(title: "iPhone X Türkiye'de", thumbnailUrl: "https://i.ytimg.com/vi/2XxWlt2uTMU/hqdefault.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLANLMLpzqJQYnpn2TLz8EfWzBhc8g", url: "https://www.youtube.com/watch?v=2XxWlt2uTMU")
var video1 = Video(title: "Merhaba", thumbnailUrl: "https://i.ytimg.com/vi/5bjW7b4fw9A/hqdefault.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLAqnpmbqLE75Mp9TrQMjYXxmMNN3g", url: "https://www.youtube.com/watch?v=5bjW7b4fw9A")
